CREATE OR REPLACE TRIGGER EAL_after_insert_almox
AFTER INSERT ON EAL_ALMOXARIFADO_TAB
FOR EACH ROW
DECLARE
BEGIN
  if (EAL_ALMOXARIFADO_TAB.CODIGALMOX = 0) then
    update EAL_ALMOXARIFADO_TAB
    set EAL_ALMOXARIFADO_TAB.CODIGALMOX = EAL_SEQ_ALMOX_ID.nextVal;
  end if
end
/
    
